package id3

var version24Params = &versionParams{
	frameIdSize:        4,
	frameSizeSize:      4,
	frameFlagsSize:     2,
	sizeUnsynchronized: true,
	frames: map[string]*frameFactory{
		"AENC": &frameFactory{description: "Audio encryption", maker: newDataFrame},
		"APIC": &frameFactory{description: "Attached picture", maker: newPictureFrame},
		"COMM": &frameFactory{description: "Comments", maker: newFullTextFrame},
		"COMR": &frameFactory{description: "Commercial frame", maker: newDataFrame},
		"ENCR": &frameFactory{description: "Encryption method registration", maker: newDataFrame},
		"EQUA": &frameFactory{description: "Equalization", maker: newDataFrame},
		"ETCO": &frameFactory{description: "Event timing codes", maker: newDataFrame},
		"GEOB": &frameFactory{description: "General encapsulated object", maker: newDataFrame},
		"GRID": &frameFactory{description: "Group identification registration", maker: newDataFrame},
		"IPLS": &frameFactory{description: "Involved people list", maker: newDataFrame},
		"LINK": &frameFactory{description: "Linked information", maker: newDataFrame},
		"MCDI": &frameFactory{description: "Music CD identifier", maker: newDataFrame},
		"MLLT": &frameFactory{description: "MPEG location lookup table", maker: newDataFrame},
		"OWNE": &frameFactory{description: "Ownership frame", maker: newDataFrame},
		"PRIV": &frameFactory{description: "Private frame", maker: newDataFrame},
		"PCNT": &frameFactory{description: "Play counter", maker: newDataFrame},
		"POPM": &frameFactory{description: "Popularimeter", maker: newDataFrame},
		"POSS": &frameFactory{description: "Position synchronisation frame", maker: newDataFrame},
		"RBUF": &frameFactory{description: "Recommended buffer size", maker: newDataFrame},
		"RVAD": &frameFactory{description: "Relative volume adjustment", maker: newDataFrame},
		"RVRB": &frameFactory{description: "Reverb", maker: newDataFrame},
		"SYLT": &frameFactory{description: "Synchronized lyric/text", maker: newDataFrame},
		"SYTC": &frameFactory{description: "Synchronized tempo codes", maker: newDataFrame},
		"TALB": &frameFactory{description: "Album/Movie/Show title", maker: newTextFrame},
		"TBPM": &frameFactory{description: "BPM (beats per minute)", maker: newTextFrame},
		"TCOM": &frameFactory{description: "Composer", maker: newTextFrame},
		"TCON": &frameFactory{description: "Content type", maker: newTextFrame},
		"TCOP": &frameFactory{description: "Copyright message", maker: newTextFrame},
		"TDAT": &frameFactory{description: "Date", maker: newTextFrame},
		"TDLY": &frameFactory{description: "Playlist delay", maker: newTextFrame},
		"TENC": &frameFactory{description: "Encoded by", maker: newTextFrame},
		"TEXT": &frameFactory{description: "Lyricist/Text writer", maker: newTextFrame},
		"TFLT": &frameFactory{description: "File type", maker: newTextFrame},
		"TIME": &frameFactory{description: "Time", maker: newTextFrame},
		"TIT1": &frameFactory{description: "Content group description", maker: newTextFrame},
		"TIT2": &frameFactory{description: "Title/songname/content description", maker: newTextFrame},
		"TIT3": &frameFactory{description: "Subtitle/Description refinement", maker: newTextFrame},
		"TKEY": &frameFactory{description: "Initial key", maker: newTextFrame},
		"TLAN": &frameFactory{description: "Language(s)", maker: newTextFrame},
		"TLEN": &frameFactory{description: "Length", maker: newTextFrame},
		"TMED": &frameFactory{description: "Media type", maker: newTextFrame},
		"TOAL": &frameFactory{description: "Original album/movie/show title", maker: newTextFrame},
		"TOFN": &frameFactory{description: "Original filename", maker: newTextFrame},
		"TOLY": &frameFactory{description: "Original lyricist(s)/text writer(s)", maker: newTextFrame},
		"TOPE": &frameFactory{description: "Original artist(s)/performer(s)", maker: newTextFrame},
		"TORY": &frameFactory{description: "Original release year", maker: newTextFrame},
		"TOWN": &frameFactory{description: "File owner/licensee", maker: newTextFrame},
		"TPE1": &frameFactory{description: "Lead performer(s)/Soloist(s)", maker: newTextFrame},
		"TPE2": &frameFactory{description: "Band/orchestra/accompaniment", maker: newTextFrame},
		"TPE3": &frameFactory{description: "Conductor/performer refinement", maker: newTextFrame},
		"TPE4": &frameFactory{description: "Interpreted, remixed, or otherwise modified by", maker: newTextFrame},
		"TPOS": &frameFactory{description: "Part of a set", maker: newTextFrame},
		"TPUB": &frameFactory{description: "Publisher", maker: newTextFrame},
		"TRCK": &frameFactory{description: "Track number/Position in set", maker: newTextFrame},
		"TRDA": &frameFactory{description: "Recording dates", maker: newTextFrame},
		"TRSN": &frameFactory{description: "Internet radio station name", maker: newTextFrame},
		"TRSO": &frameFactory{description: "Internet radio station owner", maker: newTextFrame},
		"TSIZ": &frameFactory{description: "Size", maker: newTextFrame},
		"TSRC": &frameFactory{description: "ISRC (international standard recording code)", maker: newTextFrame},
		"TSSE": &frameFactory{description: "Software/Hardware and settings used for encoding", maker: newTextFrame},
		"TYER": &frameFactory{description: "Year", maker: newTextFrame},
		"TXXX": &frameFactory{description: "User defined text information frame", maker: newDescribedFrame},
		// TODO: "UFID": &frameFactory{description: "Unique file identifier", maker: ParseIdFrame},
		"USER": &frameFactory{description: "Terms of use", maker: newDataFrame},
		"TCMP": &frameFactory{description: "Part of a compilation (iTunes extension)", maker: newTextFrame},
		"USLT": &frameFactory{description: "Unsychronized lyric/text transcription", maker: newFullTextFrame},
		"WCOM": &frameFactory{description: "Commercial information", maker: newDataFrame},
		"WCOP": &frameFactory{description: "Copyright/Legal information", maker: newDataFrame},
		"WOAF": &frameFactory{description: "Official audio file webpage", maker: newDataFrame},
		"WOAR": &frameFactory{description: "Official artist/performer webpage", maker: newDataFrame},
		"WOAS": &frameFactory{description: "Official audio source webpage", maker: newDataFrame},
		"WORS": &frameFactory{description: "Official internet radio station homepage", maker: newDataFrame},
		"WPAY": &frameFactory{description: "Payment", maker: newDataFrame},
		"WPUB": &frameFactory{description: "Publishers official webpage", maker: newDataFrame},
		"WXXX": &frameFactory{description: "User defined URL link frame", maker: newDataFrame},
	}}
